<?php

return [
    '/' => ['view' => 'auth/login', 'title' => 'Login', 'layout' => 'auth'],
    '/auth/login' => ['view' => 'auth/login', 'title' => 'Login', 'layout' => 'auth'],
    '/auth/password-request' => ['view' => 'auth/password-request', 'title' => 'Recuperar contraseña', 'layout' => 'auth'],
    '/auth/password-reset' => ['view' => 'auth/password-reset', 'title' => 'Restablecer contraseña', 'layout' => 'auth'],
    '/auth/2fa' => ['view' => 'auth/2fa', 'title' => 'Verificación 2FA', 'layout' => 'auth'],
    '/auth/tenant-select' => ['view' => 'auth/tenant-select', 'title' => 'Seleccionar establecimiento', 'layout' => 'auth'],
    '/auth/profile' => ['view' => 'auth/profile', 'title' => 'Perfil de usuario', 'layout' => 'auth'],
    '/auth/forbidden' => ['view' => 'auth/forbidden', 'title' => 'Sin permisos', 'layout' => 'auth'],
    '/auth/audit' => ['view' => 'auth/audit', 'title' => 'Auditoría', 'layout' => 'auth'],

    '/dashboard/director' => ['view' => 'dashboards/director', 'title' => 'Dashboard Director/UTP'],
    '/dashboard/teacher' => ['view' => 'dashboards/teacher', 'title' => 'Dashboard Docente'],
    '/dashboard/inspector' => ['view' => 'dashboards/inspector', 'title' => 'Dashboard Inspectoría/Convivencia'],
    '/dashboard/pie' => ['view' => 'dashboards/pie', 'title' => 'Dashboard PIE/Orientación'],
    '/dashboard/guardian' => ['view' => 'dashboards/guardian', 'title' => 'Dashboard Apoderado'],
    '/dashboard/student' => ['view' => 'dashboards/student', 'title' => 'Dashboard Estudiante'],
    '/dashboard/finance' => ['view' => 'dashboards/finance', 'title' => 'Dashboard Finanzas'],

    '/establishment/profile' => ['view' => 'establishment/profile', 'title' => 'Datos del establecimiento'],
    '/establishment/config' => ['view' => 'establishment/config', 'title' => 'Configuración académica'],
    '/establishment/catalogs' => ['view' => 'establishment/catalogs', 'title' => 'Catálogos'],
    '/establishment/academic-years' => ['view' => 'establishment/academic-years', 'title' => 'Gestión de años académicos'],
    '/establishment/courses' => ['view' => 'establishment/courses', 'title' => 'Gestión de cursos'],
    '/establishment/subjects' => ['view' => 'establishment/subjects', 'title' => 'Gestión de asignaturas'],
    '/establishment/assignments' => ['view' => 'establishment/assignments', 'title' => 'Asignación docente-curso-asignatura'],
    '/establishment/report-settings' => ['view' => 'establishment/report-settings', 'title' => 'Parametrización de reportes'],

    '/users' => ['view' => 'users/index', 'title' => 'Listado de usuarios'],
    '/users/create' => ['view' => 'users/create', 'title' => 'Crear usuario'],
    '/users/edit' => ['view' => 'users/edit', 'title' => 'Editar usuario'],
    '/users/roles' => ['view' => 'users/roles', 'title' => 'Asignar roles'],
    '/users/permissions' => ['view' => 'users/permissions', 'title' => 'Matriz de permisos'],
    '/users/audit' => ['view' => 'users/audit', 'title' => 'Bitácora de acciones'],

    '/enrollment/students' => ['view' => 'enrollment/students', 'title' => 'Listado estudiantes'],
    '/enrollment/students/show' => ['view' => 'enrollment/student-show', 'title' => 'Ficha estudiante'],
    '/enrollment/guardians' => ['view' => 'enrollment/guardians', 'title' => 'Listado apoderados'],
    '/enrollment/guardians/show' => ['view' => 'enrollment/guardian-show', 'title' => 'Ficha apoderado'],
    '/enrollment/link' => ['view' => 'enrollment/link', 'title' => 'Vincular estudiante-apoderado'],
    '/enrollment/enroll' => ['view' => 'enrollment/enroll', 'title' => 'Matrícula'],
    '/enrollment/import' => ['view' => 'enrollment/import', 'title' => 'Importación masiva'],
    '/enrollment/history' => ['view' => 'enrollment/history', 'title' => 'Historial académico'],
    '/enrollment/documents' => ['view' => 'enrollment/documents', 'title' => 'Documentos del estudiante'],

    '/attendance/daily' => ['view' => 'attendance/daily', 'title' => 'Asistencia diaria'],
    '/attendance/blocks' => ['view' => 'attendance/blocks', 'title' => 'Asistencia por bloque'],
    '/attendance/justify' => ['view' => 'attendance/justify', 'title' => 'Justificar inasistencia'],
    '/attendance/monthly' => ['view' => 'attendance/monthly', 'title' => 'Resumen mensual asistencia'],
    '/attendance/grades' => ['view' => 'attendance/grades', 'title' => 'Registro de calificaciones'],
    '/attendance/gradebook' => ['view' => 'attendance/gradebook', 'title' => 'Libro de notas'],
    '/attendance/records' => ['view' => 'attendance/records', 'title' => 'Acta de notas'],
    '/attendance/reports' => ['view' => 'attendance/reports', 'title' => 'Reportes de asistencia'],

    '/behavior/notes' => ['view' => 'behavior/notes', 'title' => 'Anotaciones'],
    '/behavior/notes/list' => ['view' => 'behavior/notes-list', 'title' => 'Listado de anotaciones'],
    '/behavior/student' => ['view' => 'behavior/student', 'title' => 'Ficha convivencia'],
    '/behavior/incidents' => ['view' => 'behavior/incidents', 'title' => 'Gestión de incidentes'],
    '/behavior/reports' => ['view' => 'behavior/reports', 'title' => 'Reporte convivencia'],

    '/curriculum/plans' => ['view' => 'curriculum/plans', 'title' => 'Planificación anual'],
    '/curriculum/units' => ['view' => 'curriculum/units', 'title' => 'Planificación unidad'],
    '/curriculum/classes' => ['view' => 'curriculum/classes', 'title' => 'Planificación clase'],
    '/curriculum/bank' => ['view' => 'curriculum/bank', 'title' => 'Banco de OA/Indicadores'],
    '/curriculum/coverage' => ['view' => 'curriculum/coverage', 'title' => 'Cobertura curricular'],
    '/curriculum/evidence' => ['view' => 'curriculum/evidence', 'title' => 'Evidencias de cobertura'],
    '/curriculum/reports' => ['view' => 'curriculum/reports', 'title' => 'Reporte cobertura'],

    '/evaluations' => ['view' => 'evaluations/index', 'title' => 'Listado evaluaciones'],
    '/evaluations/create' => ['view' => 'evaluations/create', 'title' => 'Crear evaluación'],
    '/evaluations/editor' => ['view' => 'evaluations/editor', 'title' => 'Editor de evaluación'],
    '/evaluations/bank' => ['view' => 'evaluations/bank', 'title' => 'Banco de preguntas'],
    '/evaluations/apply' => ['view' => 'evaluations/apply', 'title' => 'Aplicación de evaluación'],
    '/evaluations/auto-grade' => ['view' => 'evaluations/auto-grade', 'title' => 'Corrección automática'],
    '/evaluations/rubric' => ['view' => 'evaluations/rubric', 'title' => 'Corrección con rúbrica'],
    '/evaluations/results' => ['view' => 'evaluations/results', 'title' => 'Resultados de evaluación'],
    '/evaluations/feedback' => ['view' => 'evaluations/feedback', 'title' => 'Retroalimentación'],
    '/evaluations/remedial' => ['view' => 'evaluations/remedial', 'title' => 'Plan de reforzamiento'],
    '/evaluations/reports' => ['view' => 'evaluations/reports', 'title' => 'Reporte evaluación'],

    '/communications/inbox' => ['view' => 'communications/inbox', 'title' => 'Bandeja de comunicaciones'],
    '/communications/compose' => ['view' => 'communications/compose', 'title' => 'Enviar mensaje'],
    '/communications/broadcast' => ['view' => 'communications/broadcast', 'title' => 'Comunicado masivo'],
    '/communications/templates' => ['view' => 'communications/templates', 'title' => 'Plantillas de comunicaciones'],
    '/communications/notifications' => ['view' => 'communications/notifications', 'title' => 'Notificaciones'],
    '/communications/status' => ['view' => 'communications/status', 'title' => 'Estado entregado/leído'],
    '/communications/channels' => ['view' => 'communications/channels', 'title' => 'Configuración de canales'],

    '/reports' => ['view' => 'reports/index', 'title' => 'Centro de reportes'],
    '/reports/attendance' => ['view' => 'reports/attendance', 'title' => 'Reporte asistencia'],
    '/reports/grades' => ['view' => 'reports/grades', 'title' => 'Reporte notas'],
    '/reports/evaluations' => ['view' => 'reports/evaluations', 'title' => 'Reporte evaluación'],
    '/reports/coverage' => ['view' => 'reports/coverage', 'title' => 'Reporte cobertura curricular'],
    '/reports/behavior' => ['view' => 'reports/behavior', 'title' => 'Reporte convivencia'],
    '/reports/risk' => ['view' => 'reports/risk', 'title' => 'Reporte riesgo escolar'],
    '/reports/exports' => ['view' => 'reports/exports', 'title' => 'Exportaciones'],

    '/finance/charges' => ['view' => 'finance/charges', 'title' => 'Listado de cobros'],
    '/finance/plans' => ['view' => 'finance/plans', 'title' => 'Plan de pagos'],
    '/finance/register' => ['view' => 'finance/register', 'title' => 'Registro de pago'],
    '/finance/accounts' => ['view' => 'finance/accounts', 'title' => 'Estado de cuenta'],
    '/finance/reports' => ['view' => 'finance/reports', 'title' => 'Reporte morosidad'],
    '/finance/income' => ['view' => 'finance/income', 'title' => 'Reporte ingresos'],
    '/finance/payments' => ['view' => 'finance/payments', 'title' => 'Pagos'],

    '/system/audit' => ['view' => 'system/audit', 'title' => 'Auditoría general'],
    '/system/backups' => ['view' => 'system/backups', 'title' => 'Gestión de respaldos'],
    '/system/db-versions' => ['view' => 'system/db-versions', 'title' => 'Versionado DB'],
    '/system/health' => ['view' => 'system/health', 'title' => 'Salud del sistema'],
    '/system/help' => ['view' => 'system/help', 'title' => 'Centro de ayuda'],
];
